apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: infraesig
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30002 # Escolha uma porta diferente para o Grafana
  type: NodePort