apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: infraesig
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest #  magem recomendada
          ports:
            - containerPort: 3000 #  Porta padrão do Grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin #  Usuário admin padrão
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin #  Senha admin padrão 
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana #  Onde o Grafana armazena dados
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc #  Nome do PersistentVolumeClaim (Criar separadamente ou usar emptyDir para teste)