
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: infraesig
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # Escolha uma porta entre 30000-32767
  type: NodePort