apiVersion: v1
kind: Service
metadata:
  name: jolokia-exporter-jenkins-service
  namespace: infraesig
  labels:
    app: jolokia-exporter-jenkins
spec:
  selector:
    app: jenkins 
  ports:
    - name: prometheus
      port: 9779
      targetPort: prometheus