apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infraesig
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'jenkins'
        metrics_path: '/jolokia/prometheus'
        static_configs:
          - targets: ['jenkins:8080'] # Usando o nome do Service

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['host.docker.internal:9100'] # Ajuste necessário para k3d no Docker