apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: infraesig
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'jenkins'
        metrics_path: '/jolokia/prometheus'
        basic_auth:
          username: admin
          password: admin
        static_configs:
          - targets: ['jenkins.infraesig:8080'] 

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.infraesig:9100'] 
      
#      - job_name: 'jenkins-jolokia-exporter'
#        metrics_path: '/metrics' # Caminho padrão do jolokia-exporter para Prometheus
#        basic_auth:
#          username: admi # As credenciais do Jolokia, se configuradas
#          password: admin # As credenciais do Jolokia, se configuradas
#        kubernetes_sd_configs:
#          - role: pod
#            namespaces:
#              names:
#                - infraesig # O namespace do seu Jenkins
#        relabel_configs:
#          - source_labels: [__meta_kubernetes_pod_container_name]
#            regex: 'jolokia-exporter'
#            action: keep # Mantém apenas os Pods com o container 'jolokia-exporter'
#          - source_labels: [__address__, __meta_kubernetes_pod_container_port_number]
#            regex: '(.*);9779' # Assumindo que a porta do exporter é 9779
#            replacement: '$1'
#            target_label: __address__ # Define o endereço para scrape como IP do Pod:porta do exporter
#          - source_labels: [__meta_kubernetes_pod_name]
#            target_label: pod
#          - source_labels: [__meta_kubernetes_pod_container_name]
#            target_label: container
#          - source_labels: [__meta_kubernetes_namespace]
#            target_label: namespace
