apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: infraesig
spec:
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30005 #  Use esta porta no navegador!
  selector:
    app: prometheus